from .autor import Autor
from .cliente import Cliente
from .descarga import Descarga
from .genero import Genero
from .libro import Libro
from .libroautor import LibroAutor
from .librogenero import LibroGenero
from .prestamo import Prestamo
from .reseña import Resena
from .suscripcion import Suscripcion
from .usuario import Usuario